@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

Interface DatabaseInterface

class EmployeeManager {
    -CommandParser commandParser

    +runCommand(String line)
}

class Name {
    - String firstName
    - String lastName
}

class PhoneNumber {
    - String middleNumber
    - String lastNumber
}


class BirthDay {
    - String year
    - String month
    - String day
}

class EmployeeNumber {
    - String fullNumber
    - String shortNumber
}

class CertificationLevel {
    - String certi
}

class CareerLevel {
    - String cl
}

class Employee {
    -int id
    -EmployeeNumber employeeNum
    -Name name
    -CareerLevel cl
    -PhoneNumber phoneNum
    -BirthDay birthday
    -CertificationLevel certi

'    + getFirstName()
'    + getLastName()
}

class EmployeeField {
    + isValidString(String inputString): boolean
    + toString(): String
    + isValid(): boolean
}

interface Option {

}

class Option1 {

}

class Option2 {

}

class Option3 {

}

'class SearchManager {
'    + search(): ArrayList<Employee>
'}

class CommandParser {
    +parseCommand(String line): Command
}

class Database {
    +select(): ArrayList<Employee>
    +select(Employee employee): ArrayList<Employee>
    +insert(Employee employee): ArrayList<Employee>
    +delete(int id): ArrayList<Employee>
    +update(int id, Employee employee): ArrayList<Employee>
'    - SearchManager searchManager
    - ArrayList<Employee> employees
}

abstract class Command {
    - ArrayList<String> params
    - DatabaseInterface databaseInterface
    - ArrayList<Option> options
'    - Comparable comparable


    - print()
    + run()
}

class AddCommand {
    select()
    insert()
}

class DeleteCommand {
    select()
    delete()
}

class SearchCommand {
    select()
}

class ModifyCommand {
    select()
    update()
}
CommandParser ..> Command
EmployeeManager *--- CommandParser
Database *- Employee

'Database *-- SearchManager

Command <|-- DeleteCommand
Command <|-- SearchCommand
Command <|-- ModifyCommand

Command *- Database
Command *-- Option

Command <|-- AddCommand


Option <|-- Option1
Option <|-- Option2
Option <|-- Option3

Employee *-- PhoneNumber
Employee *-- Name
Employee *-- BirthDay
Employee *-- EmployeeNumber
Employee *-- CareerLevel
Employee *-- CertificationLevel

PhoneNumber --|> EmployeeField
Name --|> EmployeeField
BirthDay --|> EmployeeField
EmployeeNumber --|> EmployeeField
CareerLevel --|> EmployeeField
CertificationLevel --|> EmployeeField


@enduml
